### ISSUE TITLE
[General workload issue]: Action Group Missing from Alert Rules

### ISSUE THREAD

**Issue by vivsri** [Azure/azure-monitor-baseline-alerts#410] opened 2024-11-11 18:52 UTC
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Question

### Description

Hi Team,
I was able to deploy the AMBA for ALZ pattern successfully.
On further exploring I realized the alerts do get immediately created for the respected resources but they don't have an action group associated to them. Also in the param file, there's no option to supply the name of the AG.
I used the BYOAction group & now they are associated in the policies for **Deploy Azure Monitor Baseline Alerts for Service Health** && **Deploy Azure Monitor Baseline Alerts - Notification Assets**

![Image](https://github.com/user-attachments/assets/73f5aeb9-262e-4c25-bbea-68073b97d5eb)

There's no such param for the policies/initiative creating Alert rules for other resources like a storage account.

**Comment by Brunoga-MS** [comment] 2024-11-12 09:15
Hello @vivsri,
thanks for your feedback. Alert, with the exception of Service Health and Resource Health alerts, are not configured with Action Group. They are forwarded/notified using Alert Processing Rules which will allow for notification configuration at scale. This is the reason why you do not see action groups configured as part of the alert configuration. As far as the name goes, we do not offer the ability to specify the name. we use some algorithm to prefix the action groups based on the type, since you might have more than one. The action groups created during the deployment are then associated to the abovementioned APR. If you need to use your notification assets (action groups and alert processing rules) then you need to go BYO.

Let me know if this bring some clarity.

Thanks,
Bruno.

**Comment by vivsri** [comment] 2024-11-12 10:20
Hi @Brunoga-MS,
Thanks a lot for the updates.
I read the documentation & it looks like the APR is not getting created either, nor the action group.
I made a APR from the portal & used an existing AG & then the alerts started to come in.
If i wish to skip these two steps, is there a possibility to make it happen from the code we run.
Also my pipeline is green all the times :)

**Comment by Brunoga-MS** [comment] 2024-11-12 10:35
As you got, APR and Action Groups are created as part of the **_Deploy Azure Monitor Baseline Alerts - Notification Assets_** policy initiative. If both the deployment and the remediation for the above initiative were green, APR should be there together with the action groups. Bear in mind that action groups are created even if you do not specify any email, webhook, LA and so on. In this case, an empty action group associated to an APR will be created. With that said, could you please investigate if deployment and remediation were good?

**Comment by vivsri** [comment] 2024-11-12 10:41
I'll give it a fresh try & see how it behaves on a set of new Management group structure. Let's say i have an empty MG str, devoid of any subs, can i use a sub present in some other MG str or the old MG str, if I supply the sub ID the policy won't take effect right as we don't hv a sub underneath it. I'll move the only Management Sub under the new MG str & run the pipelines again. Pls Let me know if my approach makes sense.

**Comment by vivsri** [comment] 2024-11-12 10:52
Yes that part i understand, I think initially i ran the pipeline when the sub was not under the new MG. I'll move only one sub & test it out, the one im planning to move is the management Sub. It will work with just one sub too right. Pls confirm

**Comment by Brunoga-MS** [comment] 2024-11-12 10:54
Confirmed and sorry for not have understood you

**Comment by vivsri** [comment] 2024-11-12 11:58
Hey @Brunoga-MS ,
The deployment succeeded.
The e-mail address was provided.
The params are blank for     
**"BYOActionGroup": {
      "value": []
   },
    "BYOAlertProcessingRule": {
      "value": ""
    },**

The RG & the Managed Identity are in place.

The status is non compliant as below
![Image](https://github.com/user-attachments/assets/68dda9e0-0a91-4871-b349-9a149c17c00c)

I don't see any AG & APR in place under the Monitoring Section.

Shall I try to run the remediation & check, or something s wrong as we don't see the AG & APRs.

**Comment by Brunoga-MS** [comment] 2024-11-12 12:01
Yes, you need to run the remediation using the method documented at [Remediate Policies](https://azure.github.io/azure-monitor-baseline-alerts/patterns/alz/deploy/Remediate-Policies/).

**Comment by vivsri** [comment] 2024-11-12 12:02
I just found the reason I believe, but it looks like a problem in the code.

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"InvalidTemplate","message":"Deployment template validation failed: 'The template resource 'ag-AMBA-HSO TT ISM Management (Dev/Test)-001' for type 'Microsoft.Insights/actionGroups' at line '1' and column '721' has incorrect segment lengths. A nested resource type must have identical number of segments as its resource name. A root resource type must have segment length one greater than its resource name. Please see https://aka.ms/arm-syntax-resources for usage details.'."}]}

**Comment by vivsri** [comment] 2024-11-12 12:05
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"InvalidTemplate","message":"Deployment template validation failed: 'The template resource 'apr-AMBA-HSO TT ISM Management (Dev/Test)-002' for type 'Microsoft.AlertsManagement/actionRules' at line '1' and column '306' has incorrect segment lengths. A nested resource type must have identical number of segments as its resource name. A root resource type must have segment length one greater than its resource name. Please see https://aka.ms/arm-syntax-resources for usage details.'."}]}

**Comment by Brunoga-MS** [comment] 2024-11-12 12:06
That part of the code has not been touched since months ... could you please double check the parameter file format making sure the values are written correctly?

**Comment by vivsri** [comment] 2024-11-12 12:06
Sure, which one should i be looking for. As I left the BYOAG &BYOAPR as blank.

**Comment by Brunoga-MS** [comment] 2024-11-12 12:08
the one about email address(es)

**Comment by vivsri** [comment] 2024-11-12 12:10
**"ALZMonitorActionGroupEmail": {
      "value": ["testemail@abc.com"]**

Using the above format with a working e-mail address

**Comment by Brunoga-MS** [comment] 2024-11-12 12:21
looks correct and very similar to mine:

![Image](https://github.com/user-attachments/assets/613607e9-8a03-4115-890d-f6354ef48c1b)

Moreover, take a look at the known issues when using not-allowed characters for Azure resources at:
- [Failed to deploy action group(s) and/or alert processing rule(s)](https://azure.github.io/azure-monitor-baseline-alerts/patterns/alz/Known-Issues/#failed-to-deploy-action-groups-andor-alert-processing-rules)
- [Failed to edit action group(s)](https://azure.github.io/azure-monitor-baseline-alerts/patterns/alz/Known-Issues/#failed-to-edit-action-groups)

I suspect something similar to what documented there

**Comment by vivsri** [comment] 2024-11-12 12:26
Yes I checked them out but I don't believe they apply to our scenario. So if you run your code you will get to see the AG & APR's under the Monitor ![Image](https://github.com/user-attachments/assets/775490ed-481f-46c3-b3b7-0c39421d39be)
In our case there's none, due to template nesting etc. Is there a different branch I can try to run my pipeline from.

**Comment by Brunoga-MS** [comment] 2024-11-12 13:12
Which deployment method are you using? Azure pipeline? Try to point the pipeline to release 2024-11-01

**Comment by vivsri** [comment] 2024-11-12 13:39
The pipeline came out green but during remediation it fails for creation of AG with the release 2024-11-01 too.

Deployment template validation failed: 'The template resource 'ag-AMBA-SH-HSO TT ISM Management (Dev/Test)-001' for type 'Microsoft.Insights/actionGroups' at line '1' and column '721' has incorrect segment lengths. A nested resource type must have identical number of segments as its resource name. A root resource type must have segment length one greater than its resource name.

**Comment by vivsri** [comment] 2024-11-12 13:52
Finally i guess :)

![Image](https://github.com/user-attachments/assets/74b58fbf-2097-4485-9d2d-a1d10c858ca6)

**Comment by vivsri** [comment] 2024-11-12 14:03
I was the problem as usual, so as the error message in the known issues say **At least one resource name segment is invalid according to the Resource Provider specification. (Code: InvalidResourceNameFormat)**

I was sure, it can't be the name etc, but looking at the error message again & again something inside me said the name of the AG looks weird as my sub name has dashes slashes & spaces, so I simply renamed my sub to Management as u can see in the screenshot & now the remediation worked & the policies got deployed resulting in the AG & APRs.

**Comment by Brunoga-MS** [comment] 2024-11-12 14:05
Thanks to you :-). Given your feedback I am going to close this issue as resolved.

Feel free to reopen it or to create a new one should it be the case.

Thanks,
Bruno.

**Closed by Brunoga-MS** 2024-11-12 14:05 UTC
Labels: question, Pattern: ALZ :helicopter:
