### ISSUE TITLE
[Question/Feedback]: Virtual Network Gateway Point-to-site (new) setup can't be saved due to policy

### ISSUE THREAD

**Issue by woutermation** [Azure/azure-monitor-baseline-alerts#355] opened 2024-10-02 07:55 UTC
### Check for previous/existing GitHub issues

- [X] I have checked for previous/existing GitHub issues

### Description

Virtual Network Gateway Point 2 site setup can't be saved due to AMBA policy, this is an existing vpn gateway and I'm adding the p2s config to it.

Needed the config to be applied so exempt the policy for now, will look into it further later this week but wanted the issue to be logged as well.

AMBA version 2024-09-02 is deployed

Error message:

```json
Failed to save virtual network gateway 'xxxxxx'. Error: A function or parameter in policy assignment 'Deploy-AMBA-Connectivity' associated with the policy definition 'Deploy_VnetGw_ExpressRouteCpuUtil_Alert' and the policy definition reference 'ALZ_VnetGwERCpuUtil' could not be validated.
Please either fix the policy or remove the policy assignment to unblock. If using template functions, try following the tips in: https://aka.ms/policy-avoiding-template-failures.
The inner error is 'The template function 'contains' expects parameters of matching types: a dictionary and a key (string), an array and a value (object), or a string and a substring.
The provided types 'Null' and 'String' are incompatible. Please see https://aka.ms/arm-template-expressions#contains for usage details.'.
```

**Comment by lovrozagar** [comment] 2024-10-02 08:19
Hi @woutermation ,

Thank you for logging the issue. Based on the error message, it appears that the AMBA policy Deploy-AMBA-Connectivity is causing a conflict when you're trying to add the P2S configuration to your existing VPN gateway.

The root cause seems to be the contains function in the policy, which is receiving incompatible types (Null and String). You might want to investigate the following to resolve the issue:

Check Policy Assignment: Review the Deploy_VnetGw_ExpressRouteCpuUtil_Alert policy definition, specifically any contains function calls, and ensure that they are not being passed null values where a string or object is expected.

Temporary Workaround: As you suggested, temporarily exempting the policy might unblock you for now. You can remove the policy assignment and reapply the P2S configuration.

Long-term Solution: You can consider revisiting the policy to fix the root issue. It might involve updating the policy definition to handle cases where a null value is passed to the contains function.

You can refer to this guide on avoiding template failures in Azure policies: https://aka.ms/policy-avoiding-template-failures. It might provide additional insights into handling this issue.

Let me know if you need further assistance!

**Comment by Brunoga-MS** [comment] 2024-10-02 08:29
Hello everyone.
@woutermation thanks to have logged this issue. While we investigate furthermore I would like to ask @arjenhuitema if this could be related to a missing parameter in the param file.

Thanks,
Bruno.

**Comment by arjenhuitema** [comment] 2024-10-02 14:03
Hi @woutermation, thank you for bringing this to our attention.

The majority of policies in AMBA-ALZ are Deploy If Not Exists (DINE) policies. Essentially, they audit/ deploy new resources (such as Alert rules) based on existing/new resources. This does not affect or hinder modifications to the resource (Virtual Network Gateway). 

I’m happy to help with this. Could you provide more details about what's going on? The error message suggests you might be adjusting the policy definition. Could you provide more details on the process and templates used for updating your VPN Gateway configuration?

**Comment by woutermation** [comment] 2024-10-03 08:23
Hi @arjenhuitema,
I was adding a p2s configuration to an existing Virtual Network Gateway, a little bit old fashioned via the Azure portal ;-)
When saving the config the above error pops up and the config is not saved, exempting the policy with a waiver was the workaround so that I could save the configuration.

No actions on policy what so ever that I'm aware of.

**Comment by arjenhuitema** [comment] 2024-10-03 15:22
Hi @woutermation, I attempted to reproduce the issue but couldn't, I was able to modify the Virtual Network Gateway and add the point-to-site configuration. As I mentioned yesterday, deployIfNotExists effect doesn’t stop you from modifying resources, a deployIfNotExists policy definition executes a template deployment when the condition is met. 

[Azure Policy definitions deployIfNotExists effect](https://learn.microsoft.com/en-us/azure/governance/policy/concepts/effect-deploy-if-not-exists#deployifnotexists-evaluation)

> **DeployIfNotExists evaluation**
> 
> deployIfNotExists runs after a configurable delay when a Resource Provider handles a create or update subscription or resource request and returned a success status code. A template deployment occurs if there are no related resources or if the resources defined by existenceCondition don't evaluate to true. The duration of the deployment depends on the complexity of resources included in the template.
> 
> During an evaluation cycle, policy definitions with a DeployIfNotExists effect that match resources are marked as non-compliant, but no action is taken on that resource. Existing non-compliant resources can be remediated with a [remediation task](https://learn.microsoft.com/en-us/azure/governance/policy/how-to/remediate-resources).

It's curious that this occurred while making changes through the portal, since the process of adding the point to site configuration doesn't modify or impact the policies in any way. Nevertheless, the error message suggests a problem of this nature:

> Failed to save virtual network gateway 'xxxxxx'. Error: A **function or parameter in policy assignment** 'Deploy-AMBA-Connectivity' associated with the policy definition 'Deploy_VnetGw_ExpressRouteCpuUtil_Alert' and the policy definition reference 'ALZ_VnetGwERCpuUtil' could not be validated.
> 
> Please either fix the policy or remove the policy assignment to unblock. If using template functions, try following the tips in: https://aka.ms/policy-avoiding-template-failures.
> 
> The inner error is 'The template function 'contains' expects parameters of matching types: a dictionary and a key (string), an array and a value (object), or a string and a substring.
> 
> The provided types 'Null' and 'String' are incompatible. Please see https://aka.ms/arm-template-expressions#contains for usage details.'.

If I deliberately add a mistake and attempt to update a Policy, it returns a similar error:

> A function or parameter in policy 'Deploy_VnetGw_ExpressRouteCpuUtil_Alert' could not be validated. If using template functions, try following the tips in: https://aka.ms/policy-avoiding-template-failures. The inner exception 'The policy 'Deploy_VnetGw_ExpressRouteCpuUtil_Alert' has undefined parameter 'MonitorDisableTagValues' which is used in the policy rule. Please either define it in policy definition or remove the reference in policy rule.'.

Could you try the following steps?

1. Verify that the Policy Definitions and Policy Set Definitions are accurate. If the deployment hasn't been customized, consider redeploying AMBA over your current setup to ensure all definitions are properly aligned (this will also reassign the Connectivity Initiative).
2. Deploy a test Virtual Network Gateway.
3. Set up a point-to-site configuration on the test Virtual Network Gateway.
4. If the same error occurs, please inform me so we can review it together.

**Comment by woutermation** [comment] 2024-10-07 13:35
Hi @arjenhuitema 
On a new VPGW the deployment runs correct.

1. Redeployed AMBA
2. created a test Virtual Network Gateway.
3. waited for alerts to be created
4. Set up a point-to-site configuration on the test Virtual Network Gateway.
5. No error

Maybe it has something to do with the redeploy then?

**Comment by arjenhuitema** [comment] 2024-10-08 10:02
@woutermation I'm happy it worked. Examining the activity logs could shed light on what occurred, but identifying the specific cause of the earlier error is challenging at the moment because the error message and action shouldn't logically have appeared in that manner.

I will go ahead and close this issue. If you encounter any problems in the future, please let us know.

**Closed by arjenhuitema** 2024-10-08 10:02 UTC
Labels: question, Pattern: ALZ :helicopter:, Needs: Author Feedback
